name: Build flutter app and deploy it to gh-pages
on:
  workflow_dispatch:

jobs:
  buildDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone or Checkout repository
        uses: actions/checkout@v2
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ vars.REPO }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Build flutter
        run: flutter build /project
