name: Build flutter app and deploy it to gh-pages
on:
  workflow_dispatch:

jobs:
  buildDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone or Checkout repository
        uses: actions/checkout@v2
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ vars.REPO }}

      - name: Build flutter
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          run: |
            echo ${{ vars.REPO }}
            flutter build /project
